CLASS_CHOICES = ["Barbarian", "Bard", "Cleric", "Druid", "Figter", "Mage", "Wizard", "Monk", "Mistic", "Paladin",
                 "Ranger",
                 "Sorcerer", "Thief", "Ninja", "Warlock", "Defiler", "Shaman", "Invoker", "Psion"]

TITLE_CHOICES = ["Dream", "Dreamer", "Dreams", "Rainbow", "Dreaming", "Flight", "Wings", "Mist",
                 "Sky", "Wind", "Winter", "Misty", "Cloud", "Fairy", "Dragon", "End",
                 "Beginning", "Tale", "Tales", "Emperor", "Prince", "Princess", "Willow", "Birch", "Petals",
                 "Destiny", "Theft", "Thief", "Legend", "Prophecy",
                 "Spark", "Sparks", "Stream", "Streams", "Waves",
                 "Sword", "Darkness", "Swords", "Silence", "Kiss",
                 "Butterfly", "Shadow", "Ring", "Rings", "Emerald",
                 "Storm", "Storms", "Mists", "World", "Worlds",
                 "Alien", "Lord", "Lords", "Ship", "Ships", "Star",
                 "Stars", "Force", "Visions", "Vision", "Magic",
                 "Wizards", "Wizard", "Heart", "Heat", "Twins",
                 "Twilight", "Moon", "Moons", "Planet", "Shores",
                 "Pirates", "Courage", "Time", "Academy",
                 "School", "Rose", "Roses", "Stone", "Stones",
                 "Sorcerer", "Shard", "Shards", "Slave", "Slaves",
                 "Servant", "Servants", "Serpent", "Serpents",
                 "Snake", "Soul", "Souls", "Savior", "Spirit",
                 "Spirits", "Voyage", "Voyages", "Voyager", "Voyagers",
                 "Return", "Legacy", "Birth", "Healer", "Healing",
                 "Year", "Years", "Death", "Dying", "Luck", "Elves",
                 "Tears", "Touch", "Son", "Sons", "Child", "Children",
                 "Illusion", "Sliver", "Destruction", "Crying", "Weeping",
                 "Gift", "Word", "Words", "Thought", "Thoughts", "Scent",
                 "Ice", "Snow", "Night", "Silk", "Guardian", "Angel",
                 "Angels", "Secret", "Secrets", "Search", "Eye", "Eyes",
                 "Danger", "Game", "Fire", "Flame", "Flames", "Bride",
                 "Husband", "Wife", "Time", "Flower", "Flowers",
                 "Light", "Lights", "Door", "Doors", "Window", "Windows",
                 "Bridge", "Bridges", "Ashes", "Memory", "Thorn",
                 "Thorns", "Name", "Names", "Future", "Past",
                 "History", "Nothingness", "Someone",
                 "Person", "Man", "Woman", "Boy", "Girl",
                 "Way", "Mage", "Witch", "Witches", "Curse",
                 "Talisman", "Mirror", "Mirrors", "Jewel", "Jewels",
                 "Firefly", "Fireflies", "Cross", "Fantasy", "Card",
                 "Cards", "God", "Gods", "Goddess", "Evil",
                 "Warrior", "Warriors", "Virgin", "War", "Battle",
                 "Journey", "Brother", "Brothers", "Sister", "Sisters",
                 "Grave", "Voice", "Voices", "Fox", "Lion", "Wolf",
                 "Wolves", "Bunny", "Bird", "Birds", "Hero", "Crown",
                 "Sand", "Sun", "Sunlight", "Sands", "Hope", "Lust",
                 "Passion", "Love", "Hate", "Wrath", "Anger", "Revenge",
                 "Need", "Crossing", "Passage", "Rite", "Rites", "Crystal",
                 "Crystals", "Cave", "Caves", "Cavern", "Caverns", "Island",
                 "Land", "Lands", "Ocean", "Sea", "Oceans", "Seas", "Desert",
                 "Deserts", "Forest", "Forests", "Woods", "Jungle", "Jungles",
                 "Exile", "Empire", "Kingdom", "City", "Village", "Garden", "Fall",
                 "Spring", "Eve", "Dawn", "Oath", "Gold", "Cities", "Ally", "Hand",
                 "Sign", "Omen", "Court", "Courts", "Unicorn", "Pegasus", "Griffon",
                 "Farewell", "Tower", "Towers", "Heaven", "Hell", "Heavens",
                 "Hunt", "Rebirth", "Path", "Dagger", "Daggers", "Knife", "Knives",
                 "Tooth", "Teeth", "Bite", "Promise", "Price", "Queen", "King",
                 "Queens", "Kings", "Arrow", "Arrows", "Song", "Singer", "Dance",
                 "Dancer", "Dances", "Dancers", "Torture", "Lament", "Pain",
                 "Assassin", "Spy", "Spies", "Agony", "Mistress", "Tree",
                 "Trees", "Master", "Honor", "Loyalty", "Trust", "Apprentice",
                 "Prison", "Prisoner", "Phoenix", "Breath", "Horn", "Claw", "Talon",
                 "Tail", "Speaker", "Eclipse", "Scream", "Screams", "Revolution",
                 "Thrusting", "Wraith", "Phantom", "Sheep"]
